### ISSUE TITLE
Type issue when using `t_intersects` filter

### ISSUE THREAD

**Issue by bjgiraudon** [planetlabs/go-ogc#62]
Hi, 

I have been using this library for implementing cql-2 filtering in a STAC REST API using the Filters extension.

However, I came across an issue while trying to use the `t_intersects` filters.

For example with these filters:
```json
{
    "filter-lang": "cql2-json",
    "filter": {
        "op" : "and",
        "args": [
            {
                "op": "=",
                "args" : [ { "property": "collection" }, "COLLECTION.ID" ]
            },
            {
                "op": "t_intersects",
                "args": [
                    { "property": "datetime" },
                    { "interval" : [ "2020-11-11T00:00:00Z", "2020-11-12T00:00:00Z"] }
                ]
            }
        ]
    }
}
```

It seems that the `decodeExpression` function interprets the datetimes as strings and returns an error.

The `decodeInternal` function then returns with an error:

```json
{
    "error": "trouble decoding arg 1 for \"t_intersects\" op: expected date or timestamp expression, got 2020-11-11T00:00:00Z"
}
```

I will be happy to help if needed, thanks!

**Comment by tschaub** [comment]
Thanks for the report, @bjgiraudon.

I've addressed this in the v0.11.0 release.  See #63 for details.
